### PR TITLE
Saasquatch api tokens

### PR DESCRIPTION
**Pull request by davidbishoppp**
This PR addresses https://trello.com/c/iL1ifxwU/113-saasquatch-backend-oauth

Adds saasquatch API tokens to requests. Linter/prettier edited a lot of files, but primary changes are in:
SaasquatchApiModel.ts
hubspotUpdatesController.ts

### CODE REVIEW

**Comment by davidbishoppp** [comment]
[Saasquatch backend oauth](https://trello.com/c/iL1ifxwU/113-saasquatch-backend-oauth)

**Comment by lucianojd** [comment]
We're you able to successfully get the create SaaSquatch users with OAuth working?

**Comment by tolkamps1** [comment]
oh weird yea, looks like all the front-end stuff was linted. I originally hasn't included anything outside of the /src dir so that's probably why that happened.
Looks good! I have not yet pulled and tested, but code looks good.

**Review by lucianojd — APPROVED** [review]
I think we can merge this in now. Do you plan to add more calls switched to auth0?

**Review by lucianojd — APPROVED** [review]

**Review by MAsimSENG — APPROVED** [review]
Code looks good to me.

**Review by tolkamps1 — APPROVED** [review]

**Pull request merged**
