### PR TITLE
Frontend configuration screen

### PR DESCRIPTION
**Pull request by ChristopherRDunn**
This links to [ticket ](https://trello.com/c/nkSSDT2U) in Trello.

This Pr sets up routing, the login page is rendered for URLs "/" and "/login", the config page is rendered for "/configuration".

The config screen is still a bit of a  WIP, but this gets the idea of what we're thinking across.

### CODE REVIEW

**Review by nicolepeverley — COMMENTED** [review]
This is looking good! Would you be able to change the redirect in the HubSpot OAuth flow to go to the configuration page by changing line 97 in `src/routes/oauth.ts` to this?

`res.status(200).send("<script>window.opener.location = 'http://localhost:3000/configuration'; window.close();</script>");`

Maybe if you have time we could also add some more of the options that we were talking about today in the Figma https://www.figma.com/file/zPnGUrY5a53VoKfIiK5PKI/Login to show Logan were working on adding these options for both HubSpot and SaaSquatch.

**Comment by ChristopherRDunn** [comment]
I switched the redirect to head to the config page, put the HubSpot logo on top of the config screen, imported a SaaSquatch logo (not doing anything with it yet), and added a connecting fields option under the HubSpot sync.
I am looking at making some of the bigger changes we talked about Friday, but I think those big changes should be left for the next sprint, or till we get his opinion on the changes. Lmk how you feel about that

**Review by nicolepeverley — APPROVED** [review]
Looks good to me for now! We can get some feedback from Logan on our new configuration mock ups and work on it in sprint 2 👍

**Comment by MCunningham211** [comment]
Looks good in my opinion. Good idea bringing in the logo. Even if it is not used right now, it will definitely be in the future

**Review by MCunningham211 — APPROVED** [review]
This looks good to me

**Pull request merged**
