### PR TITLE
Frontend Updates, 1:1 Relationship and Temp User Database

### PR DESCRIPTION
**Pull request by nicolepeverley**
This PR checks a 1:1 relationship for SaaSquatch and Hubspot accounts and checks the regular user database when a  user tries to login with Hubspot to see if they already have an integration with a different Hubspot account. If a previous integration does exist the error message below is displayed.

Screen Shot 2021-07-22 at 3 26 21 PM

This PR is now also merged with Chris and Max's frontend updates for only posting user on final configuration page and adding a confirmation page.

I also added a warning for when third party cookies aren't enabled.

https://trello.com/c/64QYJtBQ/133-use-temp-user-database-to-check-11-relationship-on-login
https://trello.com/c/ukamNgKl/93-update-ui-for-logan
https://trello.com/c/o9k71EAn/126-create-order-confirmation-screen
https://trello.com/c/Q0mtTolQ/134-warning-to-enable-third-party-cookies

### CODE REVIEW

**Review by tolkamps1 — APPROVED** [review]
Good work team!! MVPs :)

**Review by lucianojd — APPROVED** [review]
Great work! Let's merge it in!

**Review by ChristopherRDunn — APPROVED** [review]
Looks awesome! Thanks for the great work Nicole

**Review by MCunningham211 — APPROVED** [review]
I read my way through all the changes, and I don't see any problems. This looks super good! Great work!

**Review by MAsimSENG — APPROVED** [review]
Amazing work front end team!

**Pull request merged**
