### PR TITLE
Renamed name to match import statement.

### PR DESCRIPTION
**Pull request by lucianojd**
There is an import statement in some of the components that are importing a the SaaSquatch logo with the name `SaasquatchLogo.png` instead of `SaaSquatchLogo.png`.

Contributes to the sprint goal of having the configuration on the front end.

Trello ticket: https://trello.com/c/6rXYp033

### CODE REVIEW

**Review by ChristopherRDunn — APPROVED** [review]
Looks good

**Review by nicolepeverley — APPROVED** [review]
Weird that this didn't show up before looks good nice catch!

**Comment by lucianojd** [comment]
[Fixing Dependency Errors Related To Jest](https://trello.com/c/PAINLc8S/80-fixing-dependency-errors-related-to-jest)

**Comment by lucianojd** [comment]
[Fixed Import Naming Issue With SaaSquatchLogo.png](https://trello.com/c/6rXYp033/79-fixed-import-naming-issue-with-saasquatchlogopng)

**Pull request merged**
